# Generated by Django 4.2 on 2024-02-11 09:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mng', '0024_alter_dailystatus_date_alter_expenses_exdate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailystatus',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 11, 15, 0, 40, 916531)),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='exdate',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 11, 15, 0, 40, 914532)),
        ),
        migrations.AlterField(
            model_name='mainamount',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 11, 15, 0, 40, 911533)),
        ),
        migrations.AlterField(
            model_name='purchaser',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 11, 15, 0, 40, 912532)),
        ),
        migrations.AlterField(
            model_name='sales',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 11, 15, 0, 40, 913531)),
        ),
        migrations.AlterField(
            model_name='salesdt',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 11, 15, 0, 40, 918533)),
        ),
    ]
